print("Welcome to the Band Name Generator.");city = input("What's the name of the city you grew up in?")
print(city)
pet_name= input("what's your pet's name?")
print(pet_name)
print("Your band name could be "+ city,pet_name) 